BourbonWarfare/bwmf

- f/radios/fn_acreRadioSetPlayerChannels.sqf
LR_CHANNELS_ARRAYS is defined so that index 0 is equal to channel 1 so
you may want to tweak it a bit so that everyone is in the right
platoon as I'm not as familiar with this layout.
Still a WIP but its there to start the convo.
> Added support for 148/117 radio channel defaults.

- Loadouts/bluefor_standard.hpp
The bug that made the switch to A3 default uniforms was fixed in Ace.
> Changes uniforms from Arma 3 default to RHS uniforms

- f/respawn/respawn_gui_code.sqf
- f/spect/config.hpp
- f/spect/fn_CamInit.sqf
- f/spect/fn_EventHandler.sqf
> Respawn updates

- mission.sqm
Thanks to @AACO for pointing that out to me in #46.
> Fix multiple occurrences of misspelled "Civilian"

- f/assignGear/fn_assignGearMan.sqf
- f/assignGear/fn_assignGearVehicle.sqf
Change class name and amount parsing for assignments across the board.
Add variable privatization in both Vehicle and Man gear assignment scripts.
Since this is a decently sized cleanup PR, it would be wise to review these changes carefully.
> Change assignGear for more consistent and cleaner code

- f/assignGear/fn_assignGearMan.sqf
This will correctly use the amount given, instead of adding 1 to many of the provided items.
I :shipit: to early...
> Fix incorrect gear amount being added

- description.ext
- f/assignGear/fn_assignGearMan.sqf
- f/respawn/fn_RespawnDrawMapIcons.sqf
- f/respawn/fn_RespawnLocalClient.sqf
- f/respawn/respawn_gui_code.sqf
- f/respawn/respawn_init.sqf
- f/respawn/respawn_settings.sqf
- f/spect/fn_CamInit.sqf
- f/spect/fn_DrawMarkers.sqf
- f/spect/fn_DrawTags.sqf
- f/spect/fn_EventHandler.sqf
- f/spect/fn_ForceExit.sqf
- f/spect/fn_FreeCam.sqf
- f/spect/fn_GetPlayers.sqf
- f/spect/fn_HandleCamera.sqf
- f/spect/fn_OnMapClick.sqf
- f/spect/fn_ToggleGUI.sqf
- f/spect/fn_UpdateValues.sqf
- f/spect/fn_showMenu.sqf
Changes to spec, fixed issue with assign gear
> Spec fixes

- f/pabstMarkers/defines_unitsAndGroups.sqf
> Fix Group names containing needless dash at the end

- description.ext
- f/missionConditions/fn_missionTimer.sqf
- f/spect/fn_CamInit.sqf
Only problem with the diary entry (I can see) is if someone uses skiptime in mission, otherwise it should be fine.
> Mission timer

- cleanup.bat
- f/pabstMarkers/defines_unitsAndGroups.sqf
file to remove empty lines, comments, and unused files (including unused loadouts).
HIGHLY RECOMMEND THIS IS THE STEP TAKEN BEFORE PUBLISHING YOUR MISSION.
> Cleanup file

- mission.sqm
re: http://forums.bourbonwarfare.com/viewtopic.php?f=8&t=2707#p30336
> Fix opfor engineer class names to match other sides

- f/assignGear/fn_assignGearVehicle.sqf
- f/assignGear/fn_gearErrorlogger.sqf
- f/pabstMarkers/fn_drawMap.sqf
- f/pabstMarkers/fn_serverSetupGroupID.sqf
- f/pabstMarkers/fn_setupDrawThings.sqf
- f/radios/fn_acreRadioSetPlayerChannels.sqf
- f/radios/fn_acreRadioSetup.sqf
- f/setTeamColours/fn_setTeamColours.sqf
- f/spect/fn_OnMapClick.sqf
Replaced forEach loops with count loops, where applicable. Faster inString method.
> misc optimizations

- cleanup.bat
Fix cleanup bat to properly remove 3den backup
> Fix cleanup bat to remove 3den backup

- mission.sqm
> Add refuel module, increase bleed to 10

- cfg/ACE_Settings.hpp
- init.sqf
-Moves safestart init to ace settings
-Sets up default AI skill levels
Do the skills look good?
> Configure for current potato iteration

- cfg/ACE_Settings.hpp
- cfg/CfgEventHandlers.hpp
Should make AI a little more accurate, _should_ also fix HC spawned units dropping their backpacks.
> Small AI tweak, add frame delay to gear script

- description.ext
- mission.sqm
redundant with the 3den editor.
> move loading screen text

- f/respawn/fn_RespawnLocalClient.sqf
- f/spect/fn_CamInit.sqf
Should fix the issue where people will still hear babel in spectate, should also address/add debugging for respawned people not being in the same group.
> Fix spectator babel and respawn grouping

- mission.sqm
Move to the CBA call-sign fix, should be done a while before https://github.com/BourbonWarfare/POTATO/pull/98 is merged.
> Move to CBA callign system

- Loadouts/reb_ak47_desert.hpp
- Loadouts/ru_ak74_desert.hpp
- Loadouts/ru_ak74_floral.hpp
- Loadouts/ukr_ak74_ddpm.hpp
- Loadouts/ukr_ak74_ttsko.hpp
- Loadouts/us_m4_ocp.hpp
- Loadouts/us_m4_ucp.hpp
Replace current HLC assets with incoming CUP assets
> Replace HLC with CUP

- Loadouts/common.hpp
- README.md
- description.ext
- mission.sqm
- Makes advanced medical the default
- Adds rifleman morphine
- Slight tweak to medic loadout
- Adds adds some CBA settings (ACRE API calls are getting close to being deprecated)
> Add Adv Medical as a standard

- CfgLoadouts.hpp
- Loadouts/aaf_f2000_digi.hpp
- Loadouts/brit_hk416_bs_apex.hpp
- Loadouts/brit_hk416_gs_apex.hpp
- Loadouts/brit_mx_bs.hpp
- Loadouts/brit_mx_ctrg.hpp
- Loadouts/brit_mx_gs_apex.hpp
- Loadouts/chi_qbz95_universal.hpp
- Loadouts/csat_qbz95_ghex_apex.hpp
- Loadouts/csat_qbz95_hex_apex.hpp
- Loadouts/csat_qbz95_uhex_apex.hpp
- Loadouts/csat_sama_hex.hpp
- Loadouts/csat_sama_uhex.hpp
- Loadouts/fia_tar21_gur.hpp
- Loadouts/msv_csat_qbz95_ghex_apex.hpp
- Loadouts/msv_csat_sama_hex.hpp
- Loadouts/msv_csat_sama_uhex.hpp
- Loadouts/msv_ru_ak74_emr.hpp
- Loadouts/msv_ru_ak74_emrd.hpp
- Loadouts/msv_ru_ak74_flora.hpp
- Loadouts/msv_sov_akm_ttsko.hpp
- Loadouts/ru_ak74_floral.hpp
- Loadouts/us_hk416_mtp.hpp
- Loadouts/us_hk416_trop_apex.hpp
- Loadouts/us_mx_mtp.hpp
- Loadouts/us_mx_trop_apex.hpp
I did some testing here and there, would benefit from closer eyes, but should be good assuming content is okay.
Closes #39
> Vanilla loadouts

- Loadouts/ru_ak74_floral.hpp
> give vic commander maps, compasses, etc

- README.md
Adds tags and a header to the readme
> Tags + Header

- Loadouts/aaf_f2000_digi.hpp
> remove super gl rigs from ftl

- CfgLoadouts.hpp
for https://github.com/BourbonWarfare/POTATO/pull/465
> Add supply crate loadout example

- mission.sqm
~~i need to figure out why this doesn't work even though it should (?)~~
adds 3 zeus slots with linked gmaster modules so anyone slotted always gets zeus 
Edit: also doubled spectator slots
> add zeus slots

- cleanup.bat
makes cleanup.bat work again (destructively, would be better to fix scripts folder, but this will bandaid-fix the issue)
> fix: cleanup.bat

- README.md
- description.ext
- mission.sqm
Added JFO unit marker
Updated BWMF date
Updated readme with changelog for 5.6
> JFO marker, BWMF date, Readme

- CfgLoadouts.hpp
This PR adds prefixes for relevant "nolambs" units.
> No Lambs AI - Add Relevenat Prefixes for Proper Loadouts
